language: ruby
bundler_args: --without production
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database buddy_pix_test' -U postgres
